name: SignalAir
options:
  bundleIdPrefix: com.signalair
  deploymentTarget:
    iOS: "16.0"
targets:
  SignalAir:
    type: application
    platform: iOS
    sources:
      - path: SignalAir
        excludes:
          - "*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.signalair.app
        SWIFT_VERSION: 5.9
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        ENABLE_BITCODE: false
        SWIFT_EMIT_LOC_STRINGS: true
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: SignalAir/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      release:
        SWIFT_COMPILATION_MODE: wholemodule
